image: /home/robit/colcon_ws/src/pcl2costmap/final.png
resolution: 0.1
origin: [-7.43075, -7.88589, 0.0]
map_size: [473, 285, 0.0]
occupied_thresh: 0.8 # obstacle
free_thresh: 0.35 #free
negate: 0 # 0 : white obstacle , 1 : black obstacle

